openapi: 3.0.1
info:
  title: CallDbpedia
  description: API Definition of CallDbpedia
  version: 1.0.0
servers:
- url: http://localhost:8290/callDbpedia
paths:
  /{CompanyName}:
    get:
      parameters:
      - name: CompanyName
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
