openapi: 3.0.1
info:
  title: YahooFinance
  description: API Definition of YahooFinance
  version: 1.0.0
servers:
- url: http://localhost:8290/yahoo
paths:
  /{symbol}:
    get:
      parameters:
      - name: symbol
        in: path
        required: true
        schema:
          type: string
      responses:
        default:
          description: Default response
