openapi: 3.0.1
info:
  title: AzureApi
  description: API Definition of AzureApi
  version: 1.0.0
servers:
- url: http://localhost:8290/azure
paths:
  /:
    get:
      responses:
        default:
          description: Default response
