openapi: 3.0.1
info:
  title: BackendApi
  description: API Definition of BackendApi
  version: 1.0.0
servers:
- url: http://localhost:8290/Hey
paths:
  /:
    get:
      responses:
        default:
          description: Default response
