openapi: 3.0.1
info:
  title: CsvDataIngestion
  description: API Definition of CsvDataIngestion
  version: 1.0.0
servers:
- url: http://localhost:8290/csvFile
paths:
  /:
    get:
      responses:
        default:
          description: Default response
