openapi: 3.0.1
info:
  title: DbpediaDataIntegration
  description: API Definition of DbpediaDataIntegration
  version: 1.0.0
servers:
- url: http://localhost:8290/dbpedia
paths:
  /:
    get:
      responses:
        default:
          description: Default response
