openapi: 3.0.1
info:
  title: IngestionCsv
  description: API Definition of IngestionCsv
  version: 1.0.0
servers:
- url: http://localhost:8290/csv
paths:
  /:
    post:
      responses:
        default:
          description: Default response
