openapi: 3.0.1
info:
  title: JsonIntegration
  description: API Definition of JsonIntegration
  version: 1.0.0
servers:
- url: http://localhost:8290/jsonIntegration
paths:
  /:
    post:
      responses:
        default:
          description: Default response
