openapi: 3.0.1
info:
  title: MainApi
  description: API Definition of MainApi
  version: 1.0.0
servers:
- url: http://localhost:8290/calling
paths:
  /{table}/{source}:
    get:
      parameters:
      - name: table
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: source
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
