openapi: 3.0.1
info:
  title: split
  description: API Definition of split
  version: 1.0.0
servers:
- url: http://localhost:8290/json
paths:
  /:
    post:
      responses:
        default:
          description: Default response
