openapi: 3.0.1
info:
  title: YahooDataIntegration
  description: API Definition of YahooDataIntegration
  version: 1.0.0
servers:
- url: http://localhost:8290/yahooData
paths:
  /:
    get:
      responses:
        default:
          description: Default response
